#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "linkace"
name = "LinkAce"
description.en = "A self-hosted archive to collect links of your favorite websites."
description.fr = "Une archive auto-hébergée permettant de rassembler les liens de vos sites web préférés"

version = "2.4.2~ynh1"

maintainers = ["DeMiro5001"]

[upstream]
license = "AGPL-3.0"
website = "https://www.linkace.org/"
demo = "https://demo.linkace.org/"
admindoc = "https://www.linkace.org/docs/v2/setup/"
userdoc = "https://www.linkace.org/docs/v2/application/dashboard/"
code = "https://github.com/Kovah/LinkAce/"

fund = "https://opencollective.com/linkace"

[integration]
yunohost = ">= 12.1.17"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/linkace"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

    [install.password]
    help.en = "Use the help field to add an information for the admin about this question."
    help.fr = "Utilisez le champ aide pour ajouter une information à l'intention de l'administrateur à propos de cette question."
    type = "password"

[resources]
    [resources.sources]

    [resources.sources.main]
    url = "https://github.com/Kovah/LinkAce/archive/refs/tags/v2.4.2.zip"
    sha256 = "ff411e3d8f9a986c8d097d841d0a9ef45a8b17743af249507b5feb1763a8cb98"
    in_subdir = true

    autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

#    [resources.data_dir]
# I don't see any data folder for now

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "mariadb-server, php8.4-bcmath, php8.4-mbstring, php8.4-xml, php8.4-common, php8.4-mysql"

    [resources.database]
    type = "mysql"

    [resources.composer]
    version = "2.9.2"
