#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "linkace"
name = "LinkAce"
description.en = "A self-hosted archive to collect links of your favorite websites."
description.fr = "Une archive auto-hébergée permettant de rassembler les liens de vos sites web préférés"

version = "2.5.3~ynh1"

maintainers = ["DeMiro5001"]

[upstream]
license = "AGPL-3.0"
website = "https://www.linkace.org/"
demo = "https://demo.linkace.org/"
admindoc = "https://www.linkace.org/docs/v2/setup/"
userdoc = "https://www.linkace.org/docs/v2/application/dashboard/"
code = "https://github.com/Kovah/LinkAce/"

fund = "https://opencollective.com/linkace"

[integration]
yunohost = ">= 12.1.17"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

    [install.password]
    help.en = "Use the help field to add an information for the admin about this question."
    help.fr = "Utilisez le champ aide pour ajouter une information à l'intention de l'administrateur à propos de cette question."
    type = "password"

[resources]
    [resources.sources]

    [resources.sources.main]
    url = "https://github.com/Kovah/LinkAce/archive/refs/tags/v2.5.3.tar.gz"
    sha256 = "cf6289ff81e2b4b27fb8d25f18e31aee1cb4b21b85f2a65ecca2d33597a31a97"
    in_subdir = false

    autoupdate.strategy = "latest_github_release"

    [resources.system_user]
    allow_email = true

    [resources.install_dir]

#    [resources.data_dir]
# I don't see any data folder for now

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "mariadb-server, redis-server, php8.4-bcmath, php8.4-mbstring, php8.4-xml, php8.4-common, php8.4-mysql, php8.4-curl, php8.4-zip, php8.4-intl, php8.4-gd"

    [resources.database]
    type = "mysql"
