#sub_path_only rewrite ^__PATH__$ __PATH__/ permanent;
location ^~ __PATH__ {
    alias /var/www/linkace/public;
    index index.php;

    try_files $uri @__APP__;

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass unix:/var/run/php/php__PHP_VERSION__-fpm-__APP__.sock;
        
        fastcgi_param SCRIPT_FILENAME $request_filename;
        
        fastcgi_param REMOTE_USER $remote_user;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }
}

location @__APP__ {
    rewrite __PATH__/(.*)$ __PATH__/index.php?/$1 last;
}
