#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================

secret==$(ynh_string_random --length=32)
ynh_app_setting_set --key=secret --value=$secret

admin_mail=$(ynh_user_get_info --username=$admin --key=mail)

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"

chown -R "$app:www-data" "$install_dir"

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration files..."

ynh_config_add --template="../conf/.env.example" --destination="$install_dir/.env"

chmod 600 "$install_dir/.env"
chown "$app:$app" "$install_dir/.env"

#=================================================
# APP INSTALL
#=================================================
ynh_script_progression "Installing $app..."

pushd $install_dir
    chmod +x artisan
    ynh_exec_as_app php$php_version artisan key:generate --force -n
    ynh_exec_as_app php$php_version artisan migrate --force -n
    ynh_exec_as_app php$php_version artisan setup:complete -n
    ynh_exec_as_app php$php_version artisan registeruser --admin "$admin" "$admin_mail" "$password"
popd

# file was touched by artisan, rehash it
ynh_store_file_checksum "$install_dir/.env"
secret=$(cat $install_dir/.env | grep -e ^APP_KEY | cut -c 9-)
ynh_app_setting_set --key=secret --value=$secret

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_phpfpm

ynh_config_add_nginx

ynh_config_add_logrotate

# ynh_config_add_fail2ban --logpath="/var/log/nginx/${domain}-error.log" --failregex="Regex to match into the log for a failed login"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
