#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================

secret==$(ynh_string_random --length=36)
ynh_app_setting_set --key=secret --value=$secret

admin_mail=$(ynh_user_get_info --username=$admin --key=mail)

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"

chown -R "$app:www-data" "$install_dir"

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration files..."

ynh_config_add --template="../conf/.env.example" --destination="$install_dir/.env"

chmod 400 "$install_dir/.env"
chown "$app:$app" "$install_dir/.env"

#=================================================
# INSTALL COMPOSER DEPENDENCIES
#=================================================
ynh_script_progression "Installing composer dependencies..."

#ynh_composer_exec install --no-dev

#=================================================
# APP INSTALL
#=================================================
ynh_script_progression "Installing $app..."

pushd $install_dir
    ynh_exec_as_app php$php_version artisan migrate --force -n
    ynh_exec_as_app php$php_version artisan setup:complete --force -n
    ynh_exec_as_app php$php_version artisan registeruser --admin "$admin" "$admin_mail" "$password"
popd

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_phpfpm

ynh_config_add_nginx

ynh_config_add_logrotate

# ynh_config_add_fail2ban --logpath="/var/log/nginx/${domain}-error.log" --failregex="Regex to match into the log for a failed login"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
