#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# ENSURE DOWNWARDS COMPATIBILITY
#=================================================
if [ -z "${redis_db:-}" ]; then
    redis_db=$(grep REDIS_DB= "$install_dir/.env" | sed s/REDIS_DB=//)
    ynh_app_setting_set --app="$app" --key=redis_db --value="$redis_db"
fi

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

ynh_setup_source --dest_dir="$install_dir" --full_replace

chown -R "$app:www-data" "$install_dir"

#=================================================
# APP UPGRADE
#=================================================
ynh_script_progression "Upgrading $app..."

pushd $install_dir
    chmod +x artisan
    ynh_exec_as_app php$php_version artisan migrate --force -n
    ynh_exec_as_app php$php_version artisan cache:clear -n
    ynh_exec_as_app php$php_version artisan settings:clear-cache -n
popd

chown -R "$app:www-data" "$install_dir"

# file was touched by artisan, rehash it
ynh_store_file_checksum "$install_dir/.env"
secret=$(cat $install_dir/.env | grep -e ^APP_KEY | cut -c 9-)
ynh_app_setting_set --key=secret --value=$secret

#=================================================
# REAPPLY SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_phpfpm

ynh_config_add_nginx

ynh_config_add_logrotate

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
